<a target="_blank" href="https://colab.research.google.com/github/CLYMATIC06/SQL-Practice/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [22]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [27]:
%%sql

Select orderdate,
count(DISTINCT customerkey) as total_customers

from sales
where orderdate between '2023-01-01' and '2023-12-31'
group by orderdate
order by orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers
0    2023-01-01               12
1    2023-01-02               49
2    2023-01-03               64
3    2023-01-04               78
4    2023-01-05               87
..          ...              ...
359  2023-12-27               73
360  2023-12-28               75
361  2023-12-29               55
362  2023-12-30               91
363  2023-12-31                9

[364 rows x 2 columns]

number of customers for each region on every date for 2023

In [54]:
%%sql

Select sales.orderdate,
count(DISTINCT sales.customerkey) as total_customers,
count(DISTINCT case when c.continent='Europe' then sales.customerkey end) as europe_customers,
count(DISTINCT case when c.continent='North America' then sales.customerkey end) as america_customers,
count(DISTINCT case when c.continent='Australia' then sales.customerkey end) as australia_customers

from sales
left join customer c on sales.customerkey = c.customerkey
where sales.orderdate between '2023-01-01' and '2023-12-31'
group by sales.orderdate
order by sales.orderdate
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,total_customers,europe_customers,america_customers,australia_customers
0,2023-01-01,12,6,5,1
1,2023-01-02,49,15,31,3
2,2023-01-03,64,17,44,3
3,2023-01-04,78,28,46,4
4,2023-01-05,87,22,57,8
5,2023-01-06,57,18,34,5
6,2023-01-07,99,26,66,7
7,2023-01-08,10,4,5,1
8,2023-01-09,43,10,30,3
9,2023-01-10,49,11,33,5

**Net revenue for 2022 and 2023 based on the category**

In [67]:
%%sql

Select p.categoryname as category,
# SUM(s.quantity*s.netprice*s.exchangerate) as net_rev,
SUM(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity*s.netprice*s.exchangerate end) as rev_2022,
SUM(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity*s.netprice*s.exchangerate end) as rev_2023
from sales s
left join product p on s.productkey = p.productkey
group by category
order by category
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category    rev_2022    rev_2023
0                          Audio   766938.21   688690.18
1        Cameras and camcorders   2382532.56  1983546.29
2                    Cell phones  8119665.07  6002147.63
3                      Computers 17862213.49 11650867.21
4                 Games and Toys   316127.30   270374.96
5                Home Appliances  6612446.68  5919992.87
6  Music, Movies and Audio Books  2989297.28  2180768.13
7                   TV and Video  5815336.61  4412178.23

In [71]:
%%sql
select count(distinct customerkey) as total_customers

from sales

where sales.orderdate between '2023-01-01' and '2023-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   total_customers
0            13746

In [75]:
%%sql

Select extract(month from orderdate) as month,
 count(distinct customerkey) as total_customers

 from sales

where orderdate between '2023-01-01' and '2023-12-31'

group by month
order by month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

   month  total_customers
0      1             1579
1      2             1946
2      3             1056
3      4              551
4      5             1363
5      6             1301
6      7             1126
7      8             1198
8      9             1255
9     10             1217
10    11             1246
11    12             1484

In [77]:
%%sql

WITH CustomerFirstPurchase AS (
    SELECT
        customerkey,
        MIN(orderdate) AS first_purchase_date
    FROM
        sales
    WHERE
        orderdate BETWEEN '2023-01-01' AND '2023-12-31'
    GROUP BY
        customerkey
)
SELECT
    EXTRACT(MONTH FROM first_purchase_date) AS month,
    COUNT(DISTINCT customerkey) AS new_customers_this_month
FROM
    CustomerFirstPurchase
GROUP BY
    month
ORDER BY
    month;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

   month  new_customers_this_month
0      1                      1579
1      2                      1901
2      3                      1005
3      4                       509
4      5                      1263
5      6                      1175
6      7                       991
7      8                      1045
8      9                      1062
9     10                      1008
10    11                      1024
11    12                      1184

In [81]:
%%sql

WITH CustomerFirstPurchase AS (
    SELECT
        customerkey,
        MIN(orderdate) AS first_purchase_date
    FROM
        sales
    WHERE
        orderdate BETWEEN '2023-01-01' AND '2023-12-31'
    GROUP BY
        customerkey
)

select count(distinct customerkey) as total_customers
from CustomerFirstPurchase

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   total_customers
0            13746