<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [13]:
%%sql

Select
DATE_TRUNC('month', orderdate)::date as ordermonth,
Sum(quantity*netprice*exchangerate) as revenue,
Count(Distinct customerkey)
from sales
Group By ordermonth

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   ordermonth   revenue  count
0  2015-01-01 384092.66    200
1  2015-02-01 706374.12    291
2  2015-03-01 332961.59    139
3  2015-04-01 160767.00     78
4  2015-05-01 548632.63    236
5  2015-06-01 748563.97    238
6  2015-07-01 635376.13    227
7  2015-08-01 718538.62    235
8  2015-09-01 696805.68    277
9  2015-10-01 824891.22    304

In [19]:
%%sql
# extract specific year or month to find total monthly net revenue
Select
to_char( orderdate, 'yyyy-MM') as ordermonth,
Sum(quantity*netprice*exchangerate) as revenue,
Count(Distinct customerkey)
from sales
Group By ordermonth

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    ordermonth    revenue  count
0      2015-01  384092.66    200
1      2015-02  706374.12    291
2      2015-03  332961.59    139
3      2015-04  160767.00     78
4      2015-05  548632.63    236
..         ...        ...    ...
107    2023-12 2928550.93   1484
108    2024-01 2677498.55   1340
109    2024-02 3542322.55   1718
110    2024-03 1692854.89    877
111    2024-04  483851.39    246

[112 rows x 3 columns]

In [21]:
%%sql
# extract specific year or month to find total monthly net revenue
Select
Date_part( 'month', orderdate) as ordermonth,
Sum(quantity*netprice*exchangerate) as revenue,
Count(Distinct customerkey)
from sales
Group By ordermonth

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

    ordermonth     revenue  count
0         1.00 19765401.22   7632
1         2.00 25980857.73   9741
2         3.00 13538465.09   5388
3         4.00  7056402.33   2835
4         5.00 17245023.74   6466
5         6.00 18740856.31   6714
6         7.00 14589241.23   5792
7         8.00 16161387.57   6212
8         9.00 16717883.77   6547
9        10.00 17653586.65   6733
10       11.00 17639965.04   6690
11       12.00 21318467.90   8216

In [31]:
%%sql
# extract specific year or month to find total monthly net revenue
Select
extract( YEAR from orderdate) as orderyear,
extract( Month from orderdate) as ordermonth,
Sum(quantity*netprice*exchangerate) as revenue
from sales
Group By orderyear,ordermonth
order by orderyear,ordermonth

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

    orderyear ordermonth    revenue
0        2015          1  384092.66
1        2015          2  706374.12
2        2015          3  332961.59
3        2015          4  160767.00
4        2015          5  548632.63
..        ...        ...        ...
107      2023         12 2928550.93
108      2024          1 2677498.55
109      2024          2 3542322.55
110      2024          3 1692854.89
111      2024          4  483851.39

[112 rows x 3 columns]

In [49]:
# current date and now

%%sql

Select CURRENT_DATE

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  current_date
0   2026-04-10

In [50]:
%%sql

Select NOW()

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

                               now
0 2026-04-10 10:12:26.403525+00:00

In [82]:
%%sql
Select
extract(year from s.orderdate) as sales_year,
extract(year from DATE '2023-12-31')-5 as five_year_back_ref,
p.categoryname as category,
SUM(Case when Extract(year from s.orderdate) >= Extract(year from DATE '2023-12-31')-5 then (s.quantity*s.netprice*s.exchangerate) END) as five_year_back_revenue,
SUM(s.quantity*s.netprice*s.exchangerate) as total_net_revenue_for_sales_year
From sales s
Left join product p on s.productkey = p.productkey
Group by sales_year,
five_year_back_ref,
category
order by sales_year DESC, category

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

80 rows affected.

,sales_year,five_year_back_ref,category,five_year_back_revenue,total_net_revenue_for_sales_year
0,2024,2018,Audio,209228.64,209228.64
1,2024,2018,Cameras and camcorders,635084.71,635084.71
2,2024,2018,Cell phones,1685744.55,1685744.55
3,2024,2018,Computers,2957039.62,2957039.62
4,2024,2018,Games and Toys,85867.75,85867.75
...,...,...,...,...,...
75,2015,2018,Computers,NaN,2139915.71
76,2015,2018,Games and Toys,NaN,45404.59
77,2015,2018,Home Appliances,NaN,1380875.55
78,2015,2018,"Music, Movies and Audio Books",NaN,238806.24
79,2015,2018,TV and Video,NaN,975480.06

In [96]:
%%sql
Select current_date,
s.orderdate,
p.categoryname,

SUM(s.quantity*s.netprice*s.exchangerate) as total_net_revenue_for_sales_year
from sales s
Left join product p on s.productkey = p.productkey
where orderdate >= CURRENT_DATE - INTERVAL '5 years'
Group by s.orderdate,
p.categoryname
order by s.orderdate DESC , p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8378 rows affected.

,current_date,orderdate,categoryname,total_net_revenue_for_sales_year
0,2026-04-10,2024-04-20,Audio,1545.32
1,2026-04-10,2024-04-20,Cameras and camcorders,11729.13
2,2026-04-10,2024-04-20,Cell phones,7153.64
3,2026-04-10,2024-04-20,Computers,58353.68
4,2026-04-10,2024-04-20,Games and Toys,1744.30
...,...,...,...,...
8373,2026-04-10,2021-04-10,Cell phones,2346.90
8374,2026-04-10,2021-04-10,Computers,2709.61
8375,2026-04-10,2021-04-10,Games and Toys,50.97
8376,2026-04-10,2021-04-10,"Music, Movies and Audio Books",1854.49
8377,2026-04-10,2021-04-10,TV and Video,6628.54

In [130]:
%%sql
Select
DATE_PART('year', orderdate)as orderyear,
ROUND(AVG(EXTRACT(days from AGE(deliverydate, orderdate))),2) as avg_delivery_time,
CAST(SUM(quantity*netprice*exchangerate)AS INTEGER) as total_net_revenue_for_sales_year
from sales
where orderdate >= CURRENT_DATE - INTERVAL '5 years'
Group by orderyear
order by orderyear

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

4 rows affected.

   orderyear avg_delivery_time  total_net_revenue_for_sales_year
0    2021.00              1.39                          18836254
1    2022.00              1.62                          44864557
2    2023.00              1.75                          33108566
3    2024.00              1.67                           8396527